language: java
sudo: false
before_install:
- chmod +x gradlew
install: true
addons:
  sonarcloud:
    organization: "raynoox-github"
    token:
      secure: "hjW6Sx6Nrmnh3KuZ5XFcFFIam6F5duHgK1R1IjRLoGw6kAnOKiC50KGn1RbUbwtt2EQ4JxB1mkDkM1c2hV2r5q+dZ7Mni+LfAt/v88cZgskgV+4zH+rJAzpL2d2gW2n4Y8mIWEVyXQk50t8yyd/1/VBWopDG6o1DBC8h4EwyqSjdSaRv4OwclYd7LTgItRi+UTEv4NqNwc/jt9mLK8XWaAAvjx013zbw6DgPgl8uQ9UNJXOBUTDm1kJc5pHMGnmzXJJxyB5k0lOT36wr5wZQFlTsuL1ElMJw5F03lXyqXpaaibsOSKmJeIgGNANaummnt+Rpt7ahITqaxf/zrhXbZddqZLznc6iYCOBHkGCPOKEc3ccgvXyyTPMSEaCOcU1CIAnOO/oyq90NstvhF3ZUaMgwN7faxRjU+GcTmURRhe5jYI/90Rhheo29Q0HJXwYz5GzdsWKHKsAPPbfQ1cfGYZnOOyhG9CRfkmvtQ/hjPuSyGs0b88RWQco+mFzT3bHSXbl3HdvQSQ0k+NMNI0lmqwpflstQMV5sjPDAw2eUdWZVUjs9UfGToV2pbgCcEX5o239nA1ejTrMbe1dzvHdHTrAezKGf6a1TmKxgLXWFh92pLbUiM28QDAeOlS6vPVdjui3cgdCrNbH9FtHPToFa7VRvr/aGLMi4CWeZldBOXxs="
jdk:
- oraclejdk8
script:
- "./gradlew sonarqube"
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
  - "$HOME/.gradle"
  - ".gradle"